watch_stylesheet: true
watch_config: true
debug: false
komorebi:
  start_command: "komorebic start"
  stop_command: "komorebic stop"
  reload_command: "komorebic stop && komorebic start"
bars:
  primary-bar:
    enabled: true
    screens: ['*'] 
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: true
    blur_effect:
      enabled: true
      acrylic: false 
      dark_mode: true
      round_corners: true
      border_color: None
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 5
      left: 5
      bottom: 0
      right: 5
    widgets:
      left: [
          "home", 
          "wallpapers",
          "cava",
      ]
      center: [
          "komorebi_workspaces",
        ]
      right: [
        "komorebi_active_layout",
          "memory",
          "volume",
      ]
widgets:
  home:
    type: "yasb.home.HomeWidget"
    options:
      label: "<span>\ue8e5</span>"
      menu_list:
        - { title: "Home", path: "~" }
        - { title: "Downloads", path: "~\\Downloads"}
        - { title: "Documents", path: "~\\Documents"}
        - { title: "Pictures", path: "~\\Pictures"}
        - { title: "Videos", path: "~\\Videos"}
      system_menu: true
      power_menu: true
      blur: true
      round_corners: true
      round_corners_type: "small"
      border_color: "#7aa2f7"
      alignment: "left"
      offset_left: 0
      offset_top: 0

# =================
# === KOMOREBI ACTIVE LAYOUT WIDGET ===
# =================

  komorebi_active_layout:
    type: "komorebi.active_layout.ActiveLayoutWidget"
    options:
      hide_if_offline: true
      label: "{icon}"
      layouts:
        - 'bsp'
        - 'columns'
        - 'rows'
        - 'grid'
        - 'scrolling'
        - 'vertical_stack'
        - 'horizontal_stack'
        - 'ultrawide_vertical_stack'
        - 'right_main_vertical_stack'
      layout_icons:
        bsp: "\uebeb"
        columns: "\uebf7"
        rows: "\uec01"
        grid: "\udb81\udf58"
        scrolling: "\uebf7"
        vertical_stack: "\uebee"
        horizontal_stack: "\uebf0"
        ultrawide_vertical_stack: "\uebee"
        right_main_vertical_stack: "\uebf1"
        monocle: "\uf06f"
        maximized: "\uf06f"
        floating: "\uf2d2"
        paused: "\udb83\udf89"
        tiling: "\udb81\ude40"
      callbacks:
        on_left: 'toggle_layout_menu'
        on_middle: 'next_layout'
        on_right: 'prev_layout'
      layout_menu:
        blur: true
        round_corners: true
        round_corners_type: "normal"
        border_color: "System"
        alignment: "left"
        direction: "down"
        offset_top: 2
        offset_left: 4
        show_layout_icons: true
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 1

# =================
# === WALLPAPERS WIDGET ===
# =================

  wallpapers:
    type: "yasb.wallpapers.WallpapersWidget"
    options:
      label: "<span>\uf03e</span>"
      image_path: "C:\\Users\\tamil\\OneDrive\\Desktop\\Wallpapers\\Desktop Wallpapers\\Good"
      change_automatically: false
      update_interval: 60
      gallery:
        enabled: true
        blur: true
        image_width: 220
        image_per_page: 6
        gallery_columns: 0
        show_buttons: false
        orientation: "portrait"
        image_spacing: 10
        lazy_load: true
        lazy_load_delay: 10
        lazy_load_fadein: 200
        image_corner_radius: 20
        enable_cache: true

# =================
# === MEMORY WIDGET ===
# =================

  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uf4bc</span> {virtual_mem_free}"
      label_alt: "<span>\uf4bc</span> {virtual_mem_outof}"
      update_interval: 1000
      callbacks:
        on_right: "exec cmd /c Taskmgr"

# =================
# === VOLUME WIDGET ===
# =================

  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"  # Icon for muted
        - "\uf026"  # Icon for 0-10% volume
        - "\uf027"  # Icon for 11-30% volume
        - "\uf027"  # Icon for 31-60% volume
        - "\uf028"  # Icon for 61-100% volume
      audio_menu:
        blur: true
        round_corners: true
        round_corners_type: "small"
        border_color: "#7aa2f7"
        alignment: "center"
        direction: "down"
        offset_top: 0
        show_apps: true
        show_app_labels: true
        show_app_icons: false
      callbacks:
        on_right: "toggle_mute"

# =================
# === KOMOREBI WORKSPACES WIDGET ===
# =================

  komorebi_workspaces:
    type: "komorebi.workspaces.WorkspaceWidget"
    options:
      label_offline: "Komorebi Offline"
      label_workspace_btn: "\udb81\udc3d"
      label_workspace_active_btn: "\udb81\udc3e"
      label_workspace_populated_btn: "\udb81\udc3e"
      label_default_name: ""
      label_zero_index: false
      hide_empty_workspaces: true
      hide_if_offline: false
      animation: true
      toggle_workspace_layer:
        enabled: false
        tiling_label: "Tiling"
        floating_label: "Floating"
      app_icons: 
        enabled_populated: false
        enabled_active: false
        size: 12
        max_icons: 0
        hide_label: false
        hide_duplicates: false
        hide_floating: false


# =================
# === CAVA WIDGET ===
# =================

  cava:
    type: "yasb.cava.CavaWidget"
    options:
      bar_height: 12
      min_bar_height: 0
      sensitivity: 100
      gradient: 1
      foreground: "#89b4fa"
      gradient_color_1: '#74c7ec'
      gradient_color_2: '#89b4fa'
      gradient_color_3: '#cba6f7'
      bars_number: 10
      bar_spacing: 2
      bar_width: 4
      framerate: 60
      hide_empty: true